server:
  port: 5555

zuul:
  prefix: /api


eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetchRegistry: true

# otherwise actuator endpoints are secured
management:
  security:
    enabled: false



